// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaE02O-fjBIq99G09lE6R7M3-3JyrkuiE',
    appId: '1:967526543016:web:d22fd78816b717c63f9c9d',
    messagingSenderId: '967526543016',
    projectId: 'gupshup2-fea20',
    authDomain: 'gupshup2-fea20.firebaseapp.com',
    storageBucket: 'gupshup2-fea20.appspot.com',
    measurementId: 'G-T08HRV7PWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYa7MtDvNKwvBWlsw74HL9BMxwcJ1d5Y4',
    appId: '1:967526543016:android:d50811d41c4219273f9c9d',
    messagingSenderId: '967526543016',
    projectId: 'gupshup2-fea20',
    storageBucket: 'gupshup2-fea20.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaE02O-fjBIq99G09lE6R7M3-3JyrkuiE',
    appId: '1:967526543016:web:8140549fd1a6ec003f9c9d',
    messagingSenderId: '967526543016',
    projectId: 'gupshup2-fea20',
    authDomain: 'gupshup2-fea20.firebaseapp.com',
    storageBucket: 'gupshup2-fea20.appspot.com',
    measurementId: 'G-9TF04FDZX0',
  );
}
